nginx:
  build: .
  dockerfile: docker/Dockerfile.nginx
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - api:api
api:
  build: .
  dockerfile: docker/Dockerfile.api
  restart: always
  ports:
    - 8080:8080
  links:
   - redis
  volumes:
   - .:/app
worker:
  build: .
  dockerfile: docker/Dockerfile.worker
  restart: always
  links:
   - redis
  volumes:
   -  .:/app
redis:
  restart: always
  image: redis
