api:
  image: cloudnet/prov-api
  restart: always
  ports:
    - "8080:80"
  links:
   - redis
  container_name: api
worker:
  image: cloudnet/prov-worker
  restart: always
  links:
   - redis
redis:
  restart: always
  container_name: redis
  image: redis
