api:
  image: cloudnet/prov-api
  restart: always
  ports:
    - "8080:80"
  links:
   - redis
worker:
  image: cloudnet/prov-worker
  restart: always
  links:
   - redis
redis:
  restart: always
  image: redis
