api:
  build: .
  dockerfile: Dockerfile.api
  image: cloudnet/prov-api
  restart: always
  ports:
    - "8080:80"
  links:
   - redis
worker:
  build: .
  dockerfile: Dockerfile.worker
  restart: always
  links:
   - redis
redis:
  restart: always
  image: redis
