- name: Provisions PostgreSQL (running inside Docker)
  hosts: all
  sudo: yes

  vars:
    - postgres_root_password: CliegafEnennatNu8dru

  roles:
    - unattended-upgrades
    - docker.ubuntu
    - postgres
