- name: Provisions WordPress (running inside Docker)
  hosts: all
  sudo: yes

  vars:
    - mysql_root_password: Riwerlecmainyir

  roles:
    - unattended-upgrades
    - docker.ubuntu
    - mysql
    - wordpress
