---
- name: Download and Install Weave
  get_url:
    url={{ weave_url }}
    dest={{ weave_bin }}

- name: Setup Weave Permissions
  file:
    path={{ weave_bin }}
    mode=0757

- name: Install Docker weave helper
  copy:
    src=docker-weave-run
    dest=/usr/local/bin/docker-weave-run
    owner=root
    group=root
    mode=0757

- name: Launch Weave on master
  command: weave launch --password {{ passphrase }}
  when: is_master

- name: Launch Weave on slave
  command: sudo weave launch --password {{ passphrase }} {{ master_ip }}
  when: is_slave
