---
- name: MySQL
  docker:
    name: mysql
    image: mariadb
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    volumes:
    - "/var/lib/mysql:/var/lib/mysql"
    ports:
    - "127.0.0.1:3306:3306"

- name: WordPress
  docker:
    name: wordpress
    image: wordpress
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    links:
      - "mysql:mysql"
    ports:
    - "80:80"
